### ISSUE TITLE
Cannot see private repositories in organizations

### ISSUE THREAD

**Issue by cmoro-deusto** [somerobots/Trident#10]
My account is an owner of an organization, but I cannot see the repositories within said org. I'm also a member of another organization and repositories are not show either.

**Comment by somerobots** [comment]
Totally agree this is needed! Should slot nicely with the re-worked host/project selector changes as well. I will fix this for v1.4.2.

**Comment by cmoro-deusto** [comment]
Once again, thanks a lot!

**Comment by adrianlshaw** [comment]
Any update on this?

**Comment by somerobots** [comment]
Hey @adrianlshaw I have a build that's doing this, but it's not ready yet for the TestFlight. 

I'm working evenings to improve the app (it's going through a major refactor right now!), progress is slower because I'm also freelancing in a big project until April.

May & June I'm full time on Trident again, this is when the next TestFlight build should land with this feature!
